
-- Create IFS customers table with their industries and current ML use cases
CREATE TABLE public.ifs_customers (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_name TEXT NOT NULL UNIQUE,
  industry TEXT NOT NULL,
  current_ml_usecases TEXT[], -- Array of current ML use cases they have access to
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create index for faster customer lookups
CREATE INDEX idx_ifs_customers_name ON public.ifs_customers USING btree (customer_name);
CREATE INDEX idx_ifs_customers_industry ON public.ifs_customers USING btree (industry);

-- Insert the IFS customer data from the provided list
INSERT INTO public.ifs_customers (customer_name, industry, current_ml_usecases) VALUES
('AE Rodda & Son', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('AER HOLDING SAS (EUROFEU)', 'manufacturing', ARRAY['Supply Chain Optimization']),
('AIM METALS & ALLOYS LP (American Iron & Metal)', 'manufacturing', ARRAY['Predictive Maintenance', 'Energy Consumption Optimization']),
('ALUMINUM PRECISION PRODUCTS, INC.', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Andersen & Sons Shelling, Inc.', 'manufacturing', ARRAY['Quality Control Automation']),
('Anthesis Ltd', 'service', ARRAY['Document Processing Automation', 'Customer Service Chatbots']),
('Apex Clean Energy', 'energy', ARRAY['Energy Consumption Optimization', 'Predictive Maintenance']),
('Arcwide France', 'manufacturing', ARRAY['Supply Chain Optimization']),
('Arrow Tru-Line (ATL)', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('AXIONE', 'construction', ARRAY['Supply Chain Optimization', 'Predictive Maintenance']),
('Bama Gruppen AS', 'service', ARRAY['Customer Service Chatbots', 'Document Processing Automation']),
('BAYKAL MAKINE SAN. VE TIC. A.S.', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Bertel O Steen AS', 'service', ARRAY['Customer Service Chatbots', 'Price Optimization']),
('Billerud AB', 'energy', ARRAY['Energy Consumption Optimization', 'Predictive Maintenance']),
('Blachotrapez Sp. z o.o.', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('BMA TEKNOLOJI A.S.', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('BMW (UK) Manufacturing Limited', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation', 'Supply Chain Optimization']),
('BOCCARD SERVICES', 'construction', ARRAY['Supply Chain Optimization', 'Predictive Maintenance']),
('Bonna Sabla', 'manufacturing', ARRAY['Quality Control Automation', 'Energy Consumption Optimization']),
('Borr Drilling Limited', 'energy', ARRAY['Predictive Maintenance', 'Energy Consumption Optimization']),
('BORSEN BORU SANAYI VE TIC. LTD. STI.', 'energy', ARRAY['Predictive Maintenance', 'Supply Chain Optimization']),
('BPG Holdings IV Corp', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Burt Process Equipment', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Channel Products Acquisiton, Inc.', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Churchill China Plc', 'manufacturing', ARRAY['Quality Control Automation', 'Demand Forecasting']),
('Coba International Ltd', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Cozzini LLC', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('D.H. Pace Company, Inc.', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Debon Sp. z o. o.', 'manufacturing', ARRAY['Supply Chain Optimization', 'Quality Control Automation']),
('DEMATHIEU BARD GESTION', 'construction', ARRAY['Supply Chain Optimization', 'Predictive Maintenance']),
('DEMCON management & support B.V.', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Diversified Conveyors International (DCI)', 'construction', ARRAY['Supply Chain Optimization', 'Predictive Maintenance']),
('DNASTREAM Limited', 'other', ARRAY['Document Processing Automation', 'Customer Service Chatbots']),
('DSL, LTD.', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Electrix International Limited', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Elroy Air Inc.', 'aerospace', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Enchanted Rock', 'manufacturing', ARRAY['Energy Consumption Optimization', 'Predictive Maintenance']),
('EOMMT (Empresa Operadora Metrô de Medellin)', 'service', ARRAY['Predictive Maintenance', 'Customer Service Chatbots']),
('Exela Technologies Limited', 'service', ARRAY['Document Processing Automation', 'Customer Service Chatbots']),
('Farrow and Ball', 'manufacturing', ARRAY['Quality Control Automation', 'Demand Forecasting']),
('Figeac Aero', 'aerospace', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Foam Supplies, Inc.', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('FOUNTAINE PAJOT', 'construction', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('GCX Corporation', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Global Sea Foods (Pvt) Ltd', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('GROUPE GUILLIN', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Grupo Boticario', 'manufacturing', ARRAY['Quality Control Automation', 'Demand Forecasting']),
('HAHN Group GmbH', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Hamamatsu Photonics Europe GmbH', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Heaven Hill Distilleries, Inc.', 'manufacturing', ARRAY['Quality Control Automation', 'Demand Forecasting']),
('Hindustan Aeronautics Limited (HAL)', 'aerospace', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Honeybee Robotics LLC', 'aerospace', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Hydril USA Distribution LLC', 'energy', ARRAY['Predictive Maintenance', 'Supply Chain Optimization']),
('Hypnos Limited', 'manufacturing', ARRAY['Quality Control Automation', 'Demand Forecasting']),
('IMERYS MINERALS AB', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Infranord AB', 'service', ARRAY['Predictive Maintenance', 'Customer Service Chatbots']),
('INNOVAL', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Interpath Advisory', 'service', ARRAY['Document Processing Automation', 'Customer Service Chatbots']),
('Iron Senergy Holding, LLC', 'energy', ARRAY['Energy Consumption Optimization', 'Predictive Maintenance']),
('ITI Intermodal Services, LLC', 'service', ARRAY['Supply Chain Optimization', 'Customer Service Chatbots']),
('ITOCHU Techno-Solutions Corporation', 'aerospace', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('J&E Hall', 'manufacturing', ARRAY['Predictive Maintenance', 'Energy Consumption Optimization']),
('JAMCO Corporation', 'aerospace', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Jeumont Electric', 'manufacturing', ARRAY['Predictive Maintenance', 'Energy Consumption Optimization']),
('Jones Food Company Limited', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Karo Healthcare AB', 'manufacturing', ARRAY['Quality Control Automation', 'Demand Forecasting']),
('Katun Corporation', 'manufacturing', ARRAY['Supply Chain Optimization', 'Quality Control Automation']),
('KBR Services, LLC', 'aerospace', ARRAY['Predictive Maintenance', 'Supply Chain Optimization']),
('Keyware Solutions', 'service', ARRAY['Customer Service Chatbots', 'Document Processing Automation']),
('Konica Minolta Business Solutions Europe GmbH', 'manufacturing', ARRAY['Document Processing Automation', 'Quality Control Automation']),
('KYOTEC GROUP SA', 'construction', ARRAY['Supply Chain Optimization', 'Predictive Maintenance']),
('Latham Pool Products, Inc.', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Legal & General Homes Modular Ltd', 'construction', ARRAY['Supply Chain Optimization', 'Quality Control Automation']),
('LGC Science Group Holdings Limited', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Lockheed Martin Corporation', 'aerospace', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Lymington Precision Engineers', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('M2P Engineering Pty Ltd', 'construction', ARRAY['Supply Chain Optimization', 'Predictive Maintenance']),
('Macphie Limited', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Magnaflow - Car Sound Exhaust Systems, Inc.', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('MAIASPACE', 'aerospace', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('MAILLEFER SA', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Manufactura Moderna de Metales, S.A.', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Marelec Food Technologies', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Mattr Corporation', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Meble Wójcik Spółka z ograniczoną odpowiedzialnością', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('MHP Management- und IT-Beratung GmbH', 'other', ARRAY['Document Processing Automation', 'Customer Service Chatbots']),
('Michigan State University (FRIB)', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Miller Castings Inc', 'energy', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Mir Valve Sdn. Bhd.', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Mississippi Lime Company', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('MONARCH LANDSCAPE HOLDINGS, LLC.', 'service', ARRAY['Supply Chain Optimization', 'Customer Service Chatbots']),
('Multiplex Global Ltd', 'construction', ARRAY['Supply Chain Optimization', 'Predictive Maintenance']),
('NAGANO SCIENCE CO. LTD.', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('NAŁĘCZÓW ZDRÓJ SP Z O O', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('New Fortress Energy Inc.', 'energy', ARRAY['Energy Consumption Optimization', 'Predictive Maintenance']),
('Nicklereed Unlimited', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Nordkalk', 'energy', ARRAY['Predictive Maintenance', 'Energy Consumption Optimization']),
('NORTH AMERICAN NETWORK, LLC.', 'service', ARRAY['Customer Service Chatbots', 'Document Processing Automation']),
('OmniByte Technology', 'other', ARRAY['Document Processing Automation', 'Customer Service Chatbots']),
('Paul & Co GmbH & Co KG', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Peters Surgical Groupe', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Pilanesberg Platinum Mines - (Sedibelo)', 'energy', ARRAY['Predictive Maintenance', 'Energy Consumption Optimization']),
('POLYSOUDE', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('PowerGrid Services Acquisition, LLC', 'energy', ARRAY['Predictive Maintenance', 'Energy Consumption Optimization']),
('Prevex Oy Ab', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Prodomax Automation', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('PT. PHC Indonesia', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Reaction Engines Ltd', 'aerospace', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Reden Solar', 'energy', ARRAY['Energy Consumption Optimization', 'Predictive Maintenance']),
('RK Industries LLC', 'construction', ARRAY['Supply Chain Optimization', 'Predictive Maintenance']),
('S. A. Silva & Sons Lanka (Pvt) Ltd', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Sami Figeac Aero Manufacturing Industry (SFAM)', 'aerospace', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('SANDEN RETAIL SYSTEMS CORPORATION', 'service', ARRAY['Customer Service Chatbots', 'Supply Chain Optimization']),
('SCOOBIC HOLDING S.A.', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Singapore Technologies Engineering Aerospace Systems Pte. Ltd.', 'aerospace', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('Soil Machine Dynamics', 'construction', ARRAY['Predictive Maintenance', 'Supply Chain Optimization']),
('SSA MARINE, INC.', 'service', ARRAY['Supply Chain Optimization', 'Customer Service Chatbots']),
('SSAB Europe Oy', 'energy', ARRAY['Predictive Maintenance', 'Energy Consumption Optimization']),
('STANDARD PROCESS, INC.', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Symingtons Ltd', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Tata Consultancy Services Ltd', 'other', ARRAY['Document Processing Automation', 'Customer Service Chatbots']),
('Telstra Ltd', 'telco', ARRAY['Customer Service Chatbots', 'Fraud Detection System']),
('Tennsco Corporation', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Tharsus Group Ltd', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Thermogenics Inc.', 'manufacturing', ARRAY['Predictive Maintenance', 'Energy Consumption Optimization']),
('Timberwise (UK) Ltd', 'service', ARRAY['Customer Service Chatbots', 'Document Processing Automation']),
('TINDALL CORPORATION', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Tomra Systems ASA', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Tosoh Quartz, Inc.', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('Tranter', 'manufacturing', ARRAY['Predictive Maintenance', 'Quality Control Automation']),
('University of Moratuwa', 'other', ARRAY['Document Processing Automation', 'Customer Service Chatbots']),
('Var4Advisory S.P.A.', 'manufacturing', ARRAY['Quality Control Automation', 'Document Processing Automation']),
('Vitacress Ltd', 'manufacturing', ARRAY['Quality Control Automation', 'Supply Chain Optimization']),
('Vode Lighting LLC', 'manufacturing', ARRAY['Quality Control Automation', 'Energy Consumption Optimization']),
('WJ Group Holdings Limited', 'energy', ARRAY['Predictive Maintenance', 'Energy Consumption Optimization']),
('Wyre Solutions Limited', 'manufacturing', ARRAY['Quality Control Automation', 'Predictive Maintenance']),
('YORKTEL', 'manufacturing', ARRAY['Customer Service Chatbots', 'Document Processing Automation']);

-- Enable Row Level Security (not needed for this table as it's company data, not user-specific)
-- But we'll add it for consistency
ALTER TABLE public.ifs_customers ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all authenticated users to read customer data
CREATE POLICY "Anyone can view IFS customers" 
  ON public.ifs_customers 
  FOR SELECT 
  USING (true);
